workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: 3.19.5
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/app-release.apk