workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get --no-version-check
      - name: Build Android APK
        script: flutter build apk --release --no-version-check
    artifacts:
      - build/app/outputs/apk/release/app-release.apk